platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/aspnetcore-build

inputs:
  - name: sources

outputs:
  - name: out

run:
  path: sh
  args: ["sources/ci/tasks/build.sh"]
