platform: linux

image_resource:
  type: docker-image
  source:
    repository: 192.168.0.10:5000/ci-aspnetcore-build
    tag: 2.0

inputs:
  - name: sources

outputs:
  - name: out

run:
  path: sh
  args: ["sources/ci/tasks/build.sh"]
